### ISSUE TITLE
cursorMark introduced in Solr 4.7

### ISSUE THREAD

**Issue by felixlohmeier** [ubleipzig/solrdump#2]
Hi Miku, herzlichen Dank für das hilfreiche Tool! Ich habe es gerade genutzt, um Daten aus einem alten Solr-Index zu extrahieren. Der Solr lief noch auf Version 4.1, weshalb Solrdump zunächst immer nach dem zweiten Abruf abgebrochen ist. Kein Wunder, denn die Funktion cursorMark wurde erst [mit Solr 4.7](https://issues.apache.org/jira/browse/SOLR-5463) eingeführt. Nach einem Update auf 4.7 hat es problemlos funktioniert.

Vielleicht magst Du also Solr 4.7 als requirement in die README.md aufnehmen, damit andere nicht auch darüber stolpern?

**Comment by miku** [comment]
Vielen Dank!
